#!/usr/bin/env python3 
file1 = open('E:/Python/012/31771_4_total.csv', 'r')
for line in file1:
    print(line, end='')
file1.close()
print ("1")
file2 = open('E:/Python/012/Try1.txt', 'w')
num = file2.write( "Python,Good" )
print('文档Try.txt里有',num,'个字符')
file2.close()
print ("2")
file3 = open("E:/Python/012/Try2.txt", "w")
value1 = ('FC_Bayern_Forever_Number_One', 28)
value2 = ('Stern_des_Südens',16)
s1 = str(value1)
s2 = str(value2)
file3.write(s1+s2)
print ("3")
